# version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # depends_on:
    #   - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
# <<<<<<< HEAD
#     # DATABASE_URL: "postgres://taskuser:taskpass@database:5432/taskdb"
#       DATABASE_URL: "postgres://taskuser:taskpass@db:5432/taskdb"
# =======
      DATABASE_URL: "postgres://taskuser:taskpass@db:5432/taskdb"
      REDIS_URL: "redis://redis:6379/0"
# >>>>>>> 60ea28972a4456c730605a72eb8f5c420e2c0f72
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:

